### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [guigonca/estudo-sala-de-aula#1]
Olá Guilherme.
Estou olhando o primeiro arquivo que fizemos na nossa primeira aula de HTML, e o seu documento html, está muito bem formatado e endentado, já que fizemos ele em Notepad++.
Uma observação: Não vi no seu documento um área separada para o estilo, com o uso da **TAG ``<style>``**.

OK?

**Comment by guigonca** [comment]
Bom dia professor.
Realmente eu não criei o style na area, porém é uma coisa que eu consegui assimilar bem, e estava me acostumando a usar o link puxando o css separadamente. 
Obrigado pelo feedback.

**Comment by MOVelasco** [comment]
Guilherme, bom dia.

Essa forma que você relatou é a melhor forma.
Será apresentado na próxima aula. Você poderia ter feito dessa forma.
Se já há algum conhecimento, pode aplicar. É que eu tenho que tratar todos
igualando ao nível mais baixo de conhecimento da turma.
Espero que entenda.
Grande abraço.

Em qui., 18 de ago. de 2022 às 10:54, Guilherme Gonçalves <
***@***.***> escreveu:

**Comment by guigonca** [comment]
Certo! 
Assim que for possível poderia dar uma olhada no meu projetoWEB, comecei a criar algumas coisas e fiz o commit.

**Comment by guigonca** [comment]
Mudanças feitas, conforme orientado.
